name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up -d
          echo "⏳ Waiting for containers to initialize..."
          sleep 20

      - name: Check if web container is running
        run: docker ps -a

      - name: Run test inside web container
        run: docker compose exec web curl -s http://localhost:5000/api/users || (echo "❌ Test failed" && exit 1)

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down
